services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conference_app
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Для сохранения данных

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ppostgresql+asyncpg://postgres:postgres@db/conference_app  # Строка подключения к базе данных
    ports:
      - "8000:8000"  # Проброс порта: внешний порт 8000 будет связываться с внутренним портом 8000 вашего приложения

volumes:
  db_data:  # Объявление тома для базы данных





