services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conference_app
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      - db
      - mongodb
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db/conference_app
      MONGODB_URL: mongodb://mongodb:27017/
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"

volumes:
  db_data:
  mongodb_data:
  redis_data:




